# https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md

gui:
  # Tokyonight Day
  theme:
    activeBorderColor:
      - "#b15c00"
      - "bold"
    cherryPickedCommitBgColor:
      - "#9854f1"
    cherryPickedCommitFgColor:
      - "#2e7de9"
    defaultFgColor:
      - "#3760bf"
    inactiveBorderColor:
      - "#2496ac"
    optionsTextColor:
      - "#2e7de9"
    searchingActiveBorderColor:
      - "#b15c00"
      - "bold"
    selectedLineBgColor:
      - "#b6bfe2"
    unstagedChangesColor:
      - "#c64343"
  nerdFontsVersion: "3" # nerd fonts version to use ("2" or "3"); empty means don't show nerd font icons
git:
  overrideGpg: true # prevents lazygit from spawning a separate process when using GPG
os:
  editPreset: "emacs"
keybinding:
  universal:
    prevItem: '<c-p>' # Emacs up
    nextItem: '<c-n>' # Emacs down
    gotoTop: '<c-a>' # Emacs beginning of buffer
    gotoBottom: '<c-e>' # Emacs end of buffer
    startSearch: '<c-s>' # Emacs search
    # Unbind vim keys
    prevItem-alt: <disabled>
    nextItem-alt: <disabled>
    scrollLeft: <disabled>
    scrollRight: <disabled>
